//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ttttttttttttttt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public int MaterialID { get; set; }
        public string Name { get; set; }
        public string Weight { get; set; }
        public decimal Price { get; set; }
        public int ContractID { get; set; }
        public int EmployeesID { get; set; }
    
        public virtual Contracts Contracts { get; set; }
        public virtual Employees Employees { get; set; }
    }
}
